import os
import io
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak, KeepTogether, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas

from backend.services.business_plan_generator.chart_generator import BusinessPlanChartGenerator

# Path to logo asset
LOGO_PATH = os.path.abspath(os.path.join(
    os.path.dirname(__file__), "..", "..", "..", "frontend", "src", "assets", "logo", "sme360-ai-logo.png"
))

class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute and draw total page count, 
    running header with logo, and running footer.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        if self._pageNumber == 1:
            # Suppress header/footer on cover page
            return

        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748b"))

        # Running Header
        self.setLineWidth(0.5)
        self.setStrokeColor(colors.HexColor("#cbd5e1"))
        self.line(36, 756, 576, 756)
        
        self.drawString(36, 762, "SME360 AI — AI-Assisted Business Feasibility & Growth Plan")
        
        # Draw small header logo if available
        if os.path.exists(LOGO_PATH):
            try:
                self.drawImage(LOGO_PATH, 530, 758, width=46, height=18, preserveAspectRatio=True, mask='auto')
            except Exception:
                pass

        # Running Footer
        self.line(36, 45, 576, 45)
        self.drawString(36, 32, "Confidential — Generated by SME360 AI Decision Support Engine")
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(576, 32, page_text)

        self.restoreState()


class BusinessPlanPDFGenerator:
    """
    Generates a professional, colorful PDF document for SME360 AI Business Plans using ReportLab.
    """

    @staticmethod
    def generate_pdf(report_data: dict) -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=36,
            rightMargin=36,
            topMargin=54,
            bottomMargin=54
        )

        styles = getSampleStyleSheet()
        
        # Custom Colorful Design System Styles
        primary_color = colors.HexColor("#1e3a8a") # Dark Blue
        accent_blue = colors.HexColor("#2563eb")   # Vibrant Blue
        dark_text = colors.HexColor("#0f172a")     # Slate 900
        muted_text = colors.HexColor("#475569")    # Slate 600

        title_style = ParagraphStyle(
            'CoverTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=28,
            leading=34,
            textColor=primary_color,
            spaceAfter=6
        )

        subtitle_style = ParagraphStyle(
            'CoverSubtitle',
            fontName='Helvetica-Bold',
            fontSize=12,
            leading=16,
            textColor=accent_blue,
            spaceAfter=20
        )

        h1_style = ParagraphStyle(
            'SectionH1',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=15,
            leading=18,
            textColor=primary_color,
            spaceBefore=14,
            spaceAfter=8,
            keepWithNext=True
        )

        h2_style = ParagraphStyle(
            'SectionH2',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=11,
            leading=14,
            textColor=accent_blue,
            spaceBefore=10,
            spaceAfter=4,
            keepWithNext=True
        )

        body_style = ParagraphStyle(
            'BodyDark',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9.5,
            leading=13.5,
            textColor=dark_text,
            spaceAfter=6
        )

        bullet_style = ParagraphStyle(
            'BulletDark',
            parent=body_style,
            leftIndent=12,
            firstLineIndent=-8,
            spaceAfter=4
        )

        story = []

        # =========================================================================
        # 1. COVER PAGE
        # =========================================================================
        story.append(Spacer(1, 20))
        
        # Logo on Cover
        if os.path.exists(LOGO_PATH):
            try:
                story.append(Image(LOGO_PATH, width=160, height=64))
            except Exception:
                pass
        
        story.append(Spacer(1, 30))

        # Brand Accent Bar
        story.append(HRFlowable(width="100%", thickness=5, color=accent_blue, spaceBefore=0, spaceAfter=20))

        metadata = report_data.get("metadata", {})
        biz_id = report_data.get("business_identity", {})

        story.append(Paragraph(metadata.get("system_brand", "SME360 AI"), subtitle_style))
        story.append(Paragraph("BUSINESS PLAN", title_style))
        story.append(Paragraph(metadata.get("document_subtitle", "AI-Assisted Business Feasibility & Growth Planning"), body_style))
        
        story.append(Spacer(1, 40))

        # Prepared For Box Table
        cover_box_data = [
            [Paragraph("<b>BUSINESS NAME:</b>", body_style), Paragraph(f"<b>{biz_id.get('business_name')}</b>", body_style)],
            [Paragraph("<b>CATEGORY:</b>", body_style), Paragraph(biz_id.get('business_category'), body_style)],
            [Paragraph("<b>BUSINESS STAGE:</b>", body_style), Paragraph(biz_id.get('business_stage'), body_style)],
            [Paragraph("<b>DISTRICT:</b>", body_style), Paragraph(biz_id.get('district'), body_style)],
            [Paragraph("<b>PREPARED DATE:</b>", body_style), Paragraph(metadata.get('generated_date'), body_style)],
            [Paragraph("<b>RECORD ID:</b>", body_style), Paragraph(f"<font color='#64748b'>{metadata.get('record_id')}</font>", body_style)],
        ]
        cover_table = Table(cover_box_data, colWidths=[130, 380])
        cover_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#f8fafc")),
            ('PADDING', (0,0), (-1,-1), 8),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#e2e8f0")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#f1f5f9")),
        ]))
        story.append(cover_table)

        story.append(Spacer(1, 60))
        story.append(Paragraph("<i>This document provides automated AI decision support, feasibility analysis, and personalized growth recommendations powered by SME360 AI engine.</i>", ParagraphStyle('Disclaimer', parent=body_style, fontSize=8, textColor=muted_text)))

        story.append(PageBreak())

        # =========================================================================
        # 2. EXECUTIVE SUMMARY & FEASIBILITY SNAPSHOT
        # =========================================================================
        story.append(Paragraph("1. Executive Summary & Feasibility Snapshot", h1_style))
        story.append(HRFlowable(width="100%", thickness=1.5, color=accent_blue, spaceBefore=0, spaceAfter=10))

        exec_summary = report_data.get("executive_summary", {})
        story.append(Paragraph(exec_summary.get("business_summary"), body_style))
        story.append(Spacer(1, 10))

        # Feasibility Summary Card Table
        pred_label = exec_summary.get("predicted_label", "Conditionally Feasible")
        badge_bg = colors.HexColor("#dcfce7") if pred_label == "Feasible" else colors.HexColor("#fef9c3") if "Conditionally" in pred_label else colors.HexColor("#fee2e2")
        badge_fg = colors.HexColor("#166534") if pred_label == "Feasible" else colors.HexColor("#854d0e") if "Conditionally" in pred_label else colors.HexColor("#991b1b")

        kpi_data = [
            [
                Paragraph("<b>Predicted Feasibility</b>", body_style),
                Paragraph("<b>Model Confidence</b>", body_style),
                Paragraph("<b>Available Capital</b>", body_style),
                Paragraph("<b>Target Customers</b>", body_style),
            ],
            [
                Paragraph(f"<font color='{badge_fg.hexval()}'><b>{pred_label}</b></font>", body_style),
                Paragraph(f"<b>{exec_summary.get('confidence_percent')}</b>", body_style),
                Paragraph(f"LKR {report_data['financial_overview']['available_capital_lkr']:,.0f}", body_style),
                Paragraph(f"{report_data['market_analysis']['expected_customers_per_day']} / day", body_style),
            ]
        ]
        kpi_table = Table(kpi_data, colWidths=[130, 120, 130, 130])
        kpi_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#f1f5f9")),
            ('BACKGROUND', (0,1), (-1,1), colors.HexColor("#f8fafc")),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('PADDING', (0,0), (-1,-1), 8),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#cbd5e1")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#e2e8f0")),
        ]))
        story.append(kpi_table)

        story.append(Spacer(1, 12))

        # Embedded Probability Chart
        try:
            chart_bytes = BusinessPlanChartGenerator.generate_probability_chart(exec_summary.get("probabilities", {}))
            chart_img = Image(io.BytesIO(chart_bytes), width=480, height=176)
            story.append(Paragraph("<b>Model Feasibility Probability Distribution</b>", h2_style))
            story.append(chart_img)
        except Exception:
            pass

        story.append(Spacer(1, 15))

        # =========================================================================
        # 3. BUSINESS OVERVIEW
        # =========================================================================
        story.append(Paragraph("2. Business Overview", h1_style))
        story.append(HRFlowable(width="100%", thickness=1.5, color=accent_blue, spaceBefore=0, spaceAfter=10))

        biz_ov = report_data.get("business_overview", {})
        biz_table_data = [
            [Paragraph("<b>Business Category:</b>", body_style), Paragraph(biz_ov.get("category"), body_style), Paragraph("<b>Entrepreneur Experience:</b>", body_style), Paragraph(f"{biz_ov.get('experience_years')} Years", body_style)],
            [Paragraph("<b>Business Stage:</b>", body_style), Paragraph(biz_ov.get("stage"), body_style), Paragraph("<b>Available Staffing:</b>", body_style), Paragraph(f"{biz_ov.get('staff_count')} Person(s)", body_style)],
            [Paragraph("<b>Operating District:</b>", body_style), Paragraph(biz_ov.get("district"), body_style), Paragraph("<b>Market Competition:</b>", body_style), Paragraph(biz_ov.get("competition_level"), body_style)],
        ]
        biz_table = Table(biz_table_data, colWidths=[120, 135, 130, 125])
        biz_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#ffffff")),
            ('PADDING', (0,0), (-1,-1), 6),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#e2e8f0")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#f1f5f9")),
        ]))
        story.append(biz_table)

        story.append(Spacer(1, 15))

        # =========================================================================
        # 4. FINANCIAL & OPERATIONAL PLAN
        # =========================================================================
        story.append(Paragraph("3. Financial & Operational Plan", h1_style))
        story.append(HRFlowable(width="100%", thickness=1.5, color=accent_blue, spaceBefore=0, spaceAfter=10))

        fin = report_data.get("financial_overview", {})
        ops = report_data.get("operational_plan", {})

        fin_data = [
            [Paragraph("<b>Financial Metric</b>", body_style), Paragraph("<b>Amount (LKR) / Status</b>", body_style), Paragraph("<b>Strategic Planning Guidance</b>", body_style)],
            [Paragraph("Available Starting Capital", body_style), Paragraph(f"LKR {fin.get('available_capital_lkr'):,.0f}", body_style), Paragraph(fin.get("guidance_summary"), body_style)],
            [Paragraph("Monthly Operating Budget", body_style), Paragraph(f"LKR {fin.get('monthly_budget_lkr'):,.0f}", body_style), Paragraph("Includes inventory, rent, utilities, and staffing allocation.", body_style)],
            [Paragraph("Target Unit Price", body_style), Paragraph(f"LKR {fin.get('expected_price_lkr'):,.0f}", body_style), Paragraph("Expected average selling price per product/service unit.", body_style)],
            [Paragraph("Estimated Monthly Revenue", body_style), Paragraph(f"LKR {fin.get('estimated_monthly_revenue_lkr'):,.0f}", body_style), Paragraph("Model estimation based on target daily customer volume.", body_style)],
        ]
        fin_table = Table(fin_data, colWidths=[150, 130, 230])
        fin_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), primary_color),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('PADDING', (0,0), (-1,-1), 6),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#cbd5e1")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#e2e8f0")),
        ]))
        
        # Color table headers white
        for col_idx in range(3):
            fin_data[0][col_idx] = Paragraph(f"<font color='#ffffff'><b>{fin_data[0][col_idx].text.replace('<b>','').replace('</b>','')}</b></font>", body_style)

        story.append(fin_table)

        story.append(Spacer(1, 15))

        # =========================================================================
        # 5. KEY BUSINESS FACTORS (POSITIVE ENABLERS & RISK HURDLES)
        # =========================================================================
        story.append(Paragraph("4. Key Business Factors", h1_style))
        story.append(HRFlowable(width="100%", thickness=1.5, color=accent_blue, spaceBefore=0, spaceAfter=10))

        factors = report_data.get("key_business_factors", {})
        positives = factors.get("positive_enablers", [])
        negatives = factors.get("risk_hurdles", [])

        story.append(Paragraph("<b>Top Positive Supporting Factors (+):</b>", h2_style))
        for item in positives:
            feat_name = item.get('feature', '').replace('_', ' ').title()
            feat_val = item.get('feature_value', 'N/A')
            story.append(Paragraph(f"• <b>{feat_name}</b> (Recorded Value: {feat_val}) — Provided strong positive support for predicted feasibility.", bullet_style))

        story.append(Spacer(1, 8))
        story.append(Paragraph("<b>Areas Needing Strategic Attention (-):</b>", h2_style))
        for item in negatives:
            feat_name = item.get('feature', '').replace('_', ' ').title()
            feat_val = item.get('feature_value', 'N/A')
            story.append(Paragraph(f"• <b>{feat_name}</b> (Recorded Value: {feat_val}) — Identified risk hurdle requiring resource or operational mitigation.", bullet_style))

        story.append(Spacer(1, 15))

        # =========================================================================
        # 6. STRATEGY PRIORITIES & OPTIONS (TOPSIS MULTI-CRITERIA)
        # =========================================================================
        story.append(Paragraph("5. Strategy Priorities & Options Comparison", h1_style))
        story.append(HRFlowable(width="100%", thickness=1.5, color=accent_blue, spaceBefore=0, spaceAfter=10))

        strat_prio = report_data.get("strategy_priorities", {})
        active_strat = strat_prio.get("selected_strategy_name") or strat_prio.get("top_recommended_strategy", "Controlled Growth")
        ai_top = strat_prio.get("ai_top_strategy", "Hybrid Digital & Local Delivery Model")
        ai_score = strat_prio.get("ai_top_score", "0.8417")
        is_user_sel = strat_prio.get("is_user_selected", False)

        if is_user_sel:
            story.append(Paragraph(f"<b>Operational Plan Strategy (Adopted by Entrepreneur):</b> <font color='#059669'><b>{active_strat}</b></font>", body_style))
            story.append(Paragraph(f"<font color='#64748b' size='8'><i>*Note: Founder customized this operational plan based on evaluated strategic options. AI MCDM Benchmark (#1): {ai_top} (Score: {ai_score}). All milestones, financial targets, and operational plans are tailored to {active_strat}.</i></font>", body_style))
        else:
            story.append(Paragraph(f"<b>AI Recommended Direction:</b> <font color='#2563eb'><b>{active_strat}</b></font> (Decision Support Score: {ai_score})", body_style))
        story.append(Spacer(1, 8))

        ranked_strats = strat_prio.get("ranked_strategies", [])
        strat_rows = [
            [Paragraph("<font color='#ffffff'><b>Rank</b></font>", body_style), Paragraph("<font color='#ffffff'><b>Strategy Name</b></font>", body_style), Paragraph("<font color='#ffffff'><b>Focus Area</b></font>", body_style), Paragraph("<font color='#ffffff'><b>Est. Capital</b></font>", body_style), Paragraph("<font color='#ffffff'><b>Score</b></font>", body_style)]
        ]
        for idx, s in enumerate(ranked_strats):
            s_name = s.get("strategy_name", f"Option {idx+1}")
            s_focus = s.get("strategic_focus", "Growth")
            s_cap = f"LKR {s.get('estimated_capital_required_lkr', 0):,.0f}" if isinstance(s.get('estimated_capital_required_lkr'), (int, float)) else "N/A"
            s_score = str(s.get("topsis_score", "N/A"))
            strat_rows.append([
                Paragraph(f"#{idx+1}", body_style),
                Paragraph(f"<b>{s_name}</b>", body_style),
                Paragraph(s_focus, body_style),
                Paragraph(s_cap, body_style),
                Paragraph(s_score, body_style)
            ])

        strat_table = Table(strat_rows, colWidths=[40, 180, 130, 100, 60])
        strat_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), primary_color),
            ('PADDING', (0,0), (-1,-1), 6),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#cbd5e1")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#e2e8f0")),
        ]))
        story.append(strat_table)

        story.append(Spacer(1, 15))

        # =========================================================================
        # 7. TIME-PHASED ACTION ROADMAP
        # =========================================================================
        story.append(Paragraph("6. Time-Phased Action Roadmap", h1_style))
        story.append(HRFlowable(width="100%", thickness=1.5, color=accent_blue, spaceBefore=0, spaceAfter=10))

        roadmap = report_data.get("action_roadmap", {})
        
        story.append(Paragraph("<b>Phase 1: Immediate Launch Preparation (0 – 3 Months)</b>", h2_style))
        for item in roadmap.get("phase_1", []):
            story.append(Paragraph(f"• {item}", bullet_style))

        story.append(Spacer(1, 6))
        story.append(Paragraph("<b>Phase 2: Operational Stabilization (3 – 12 Months)</b>", h2_style))
        for item in roadmap.get("phase_2", []):
            story.append(Paragraph(f"• {item}", bullet_style))

        story.append(Spacer(1, 6))
        story.append(Paragraph("<b>Phase 3: Growth & Expansion (1 Year+)</b>", h2_style))
        for item in roadmap.get("phase_3", []):
            story.append(Paragraph(f"• {item}", bullet_style))

        story.append(Spacer(1, 15))

        # =========================================================================
        # 8. ASSUMPTIONS & DISCLOSURES
        # =========================================================================
        story.append(Paragraph("7. Assumptions & Important Disclosures", h1_style))
        story.append(HRFlowable(width="100%", thickness=1.5, color=accent_blue, spaceBefore=0, spaceAfter=10))

        assumptions = report_data.get("assumptions_and_considerations", [])
        for item in assumptions:
            story.append(Paragraph(f"• {item}", bullet_style))

        # Build document
        doc.build(story, canvasmaker=NumberedCanvas)
        buffer.seek(0)
        return buffer.getvalue()
