import os
import io
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak, KeepTogether, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas

from backend.services.business_plan_generator.chart_generator import BusinessPlanChartGenerator

# Path to logo asset
LOGO_PATH = os.path.abspath(os.path.join(
    os.path.dirname(__file__), "..", "..", "..", "frontend", "src", "assets", "logo", "sme360-ai-logo.png"
))

class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute and draw total page count, 
    running header with logo, and running footer.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()  # type: ignore[attr-defined]

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        if self.getPageNumber() == 1:
            # Suppress header/footer on cover page
            return

        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748b"))

        # Running Header
        self.setLineWidth(0.5)
        self.setStrokeColor(colors.HexColor("#cbd5e1"))
        self.line(36, 756, 576, 756)
        
        self.drawString(36, 762, "SME360 AI — AI-Based Feasibility Analysis & Strategic Business Plan")
        
        if os.path.exists(LOGO_PATH):
            try:
                self.drawImage(LOGO_PATH, 530, 758, width=46, height=18, preserveAspectRatio=True, mask='auto')
            except Exception:
                pass

        # Running Footer
        self.line(36, 45, 576, 45)
        self.drawString(36, 32, "Confidential — Generated by SME360 AI Decision Support Engine")
        page_text = f"Page {self.getPageNumber()} of {page_count}"
        self.drawRightString(576, 32, page_text)

        self.restoreState()


class BusinessPlanPDFGenerator:
    """
    Generates a professional, research-grounded, colorful PDF document for SME360 AI Business Plans
    using ReportLab adhering strictly to the 5 Decision-Support Sections.
    """

    @staticmethod
    def generate_pdf(report_data: dict) -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=36,
            rightMargin=36,
            topMargin=54,
            bottomMargin=54
        )

        styles = getSampleStyleSheet()
        
        # Color Palette
        primary_color = colors.HexColor("#1e3a8a")  # Dark Blue
        accent_blue = colors.HexColor("#2563eb")    # Vibrant Blue
        dark_text = colors.HexColor("#0f172a")      # Slate 900
        muted_text = colors.HexColor("#475569")     # Slate 600
        emerald = colors.HexColor("#059669")        # Green

        title_style = ParagraphStyle(
            'CoverTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=26,
            leading=32,
            textColor=primary_color,
            spaceAfter=6
        )

        subtitle_style = ParagraphStyle(
            'CoverSubtitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=11,
            leading=15,
            textColor=accent_blue,
            spaceAfter=18
        )

        h1_style = ParagraphStyle(
            'SectionH1',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=13,
            leading=16,
            textColor=primary_color,
            spaceBefore=14,
            spaceAfter=6,
            keepWithNext=True
        )

        h2_style = ParagraphStyle(
            'SectionH2',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=10,
            leading=13,
            textColor=accent_blue,
            spaceBefore=8,
            spaceAfter=4,
            keepWithNext=True
        )

        body_style = ParagraphStyle(
            'BodyDark',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9,
            leading=13,
            textColor=dark_text,
            spaceAfter=5
        )

        bullet_style = ParagraphStyle(
            'BulletDark',
            parent=body_style,
            leftIndent=12,
            firstLineIndent=-8,
            spaceAfter=3
        )

        story = []

        # =========================================================================
        # COVER PAGE
        # =========================================================================
        story.append(Spacer(1, 20))
        if os.path.exists(LOGO_PATH):
            try:
                story.append(Image(LOGO_PATH, width=150, height=60))
            except Exception:
                pass
        
        story.append(Spacer(1, 25))
        story.append(HRFlowable(width="100%", thickness=4, color=accent_blue, spaceBefore=0, spaceAfter=18))

        metadata = report_data.get("metadata", {})
        biz_id = report_data.get("business_identity", {})

        story.append(Paragraph(metadata.get("system_brand", "SME360 AI"), subtitle_style))
        story.append(Paragraph("STRATEGIC BUSINESS PLAN", title_style))
        story.append(Paragraph(metadata.get("document_subtitle", "AI-Assisted Business Feasibility & Personalized Growth Report"), body_style))
        
        story.append(Spacer(1, 35))

        cover_box_data = [
            [Paragraph("<b>BUSINESS NAME:</b>", body_style), Paragraph(f"<b>{biz_id.get('business_name')}</b>", body_style)],
            [Paragraph("<b>CATEGORY:</b>", body_style), Paragraph(biz_id.get('business_category'), body_style)],
            [Paragraph("<b>BUSINESS STAGE:</b>", body_style), Paragraph(biz_id.get('business_stage'), body_style)],
            [Paragraph("<b>DISTRICT & PROVINCE:</b>", body_style), Paragraph(f"{biz_id.get('district')}, {biz_id.get('province')}", body_style)],
            [Paragraph("<b>PREPARED DATE:</b>", body_style), Paragraph(metadata.get('generated_date'), body_style)],
            [Paragraph("<b>RECORD ID:</b>", body_style), Paragraph(f"<font color='#64748b'>{metadata.get('record_id')}</font>", body_style)],
        ]
        cover_table = Table(cover_box_data, colWidths=[130, 380])
        cover_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#f8fafc")),
            ('PADDING', (0,0), (-1,-1), 7),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#e2e8f0")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#f1f5f9")),
        ]))
        story.append(cover_table)

        story.append(Spacer(1, 50))
        story.append(Paragraph("<i>This report represents the explainable output of the SME360 AI decision support pipeline, synthesizing machine learning feasibility prediction, SHAP attribution, TOPSIS ranking, and personalized strategic planning.</i>", ParagraphStyle('Disclaimer', parent=body_style, fontSize=8, textColor=muted_text)))

        story.append(PageBreak())

        # =========================================================================
        # SECTION 01 — BUSINESS & MARKET OVERVIEW
        # =========================================================================
        sec_01 = report_data.get("section_01", {})
        story.append(Paragraph("SECTION 01 — BUSINESS & MARKET OVERVIEW", h1_style))
        story.append(HRFlowable(width="100%", thickness=1.5, color=accent_blue, spaceBefore=0, spaceAfter=8))

        # 1.1 Business Summary Table
        summary_info = sec_01.get("business_summary", {})
        story.append(Paragraph("<b>1.1 Business Identity & Summary</b>", h2_style))
        sum_rows = [
            [Paragraph("<b>Business Name:</b>", body_style), Paragraph(summary_info.get("business_name", "N/A"), body_style), Paragraph("<b>Category:</b>", body_style), Paragraph(summary_info.get("business_category", "N/A"), body_style)],
            [Paragraph("<b>Business Stage:</b>", body_style), Paragraph(summary_info.get("business_stage", "N/A"), body_style), Paragraph("<b>Business Model:</b>", body_style), Paragraph(summary_info.get("business_model", "N/A"), body_style)],
            [Paragraph("<b>Operating Location:</b>", body_style), Paragraph(f"{summary_info.get('district')}, {summary_info.get('province')}", body_style), Paragraph("<b>Proposed Action:</b>", body_style), Paragraph(summary_info.get("proposed_action", "N/A"), body_style)],
        ]
        sum_table = Table(sum_rows, colWidths=[110, 145, 110, 145])
        sum_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#f8fafc")),
            ('PADDING', (0,0), (-1,-1), 5),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#e2e8f0")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#f1f5f9")),
        ]))
        story.append(sum_table)

        # Concept narrative
        concept = sec_01.get("business_concept", {})
        story.append(Spacer(1, 6))
        story.append(Paragraph(f"<b>Business Concept:</b> {concept.get('concept_overview', '')}", body_style))
        if summary_info.get("business_description") and summary_info.get("business_description") != "Information not provided":
            story.append(Paragraph(f"<b>Entrepreneur Objectives:</b> {summary_info.get('business_description')}", body_style))

        # 1.2 Market & Competition Overview
        market = sec_01.get("market_overview", {})
        comp = sec_01.get("competition", {})
        loc = sec_01.get("location", {})

        story.append(Spacer(1, 6))
        story.append(Paragraph("<b>1.2 Market, Competition & Location Analysis</b>", h2_style))
        mkt_rows = [
            [Paragraph("<b>Target Market Catchment:</b>", body_style), Paragraph(market.get("target_market", "N/A"), body_style), Paragraph("<b>Customer Demand Score:</b>", body_style), Paragraph(str(market.get("customer_demand_score", "N/A")), body_style)],
            [Paragraph("<b>Target Daily Footfall:</b>", body_style), Paragraph(f"{market.get('expected_customers_per_day', 0)} Customers / Day", body_style), Paragraph("<b>Expected Unit Price:</b>", body_style), Paragraph(f"LKR {market.get('expected_selling_price_lkr', 0):,.2f}", body_style)],
            [Paragraph("<b>Competition Level:</b>", body_style), Paragraph(comp.get("competition_level", "Moderate"), body_style), Paragraph("<b>Location Suitability:</b>", body_style), Paragraph(str(loc.get("location_suitability_score", "N/A")), body_style)],
        ]
        mkt_table = Table(mkt_rows, colWidths=[130, 125, 125, 130])
        mkt_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#ffffff")),
            ('PADDING', (0,0), (-1,-1), 5),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#e2e8f0")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#f1f5f9")),
        ]))
        story.append(mkt_table)

        story.append(Spacer(1, 12))

        # =========================================================================
        # SECTION 02 — AI FEASIBILITY & KEY INSIGHTS
        # =========================================================================
        sec_02 = report_data.get("section_02", {})
        story.append(Paragraph("SECTION 02 — AI FEASIBILITY & KEY INSIGHTS", h1_style))
        story.append(HRFlowable(width="100%", thickness=1.5, color=accent_blue, spaceBefore=0, spaceAfter=8))

        feas = sec_02.get("feasibility_assessment", {})
        pred_label = feas.get("final_predicted_label", "Conditionally Feasible")
        probs = feas.get("probabilities", {})

        badge_bg = colors.HexColor("#dcfce7") if pred_label == "Feasible" else colors.HexColor("#fef9c3") if "Conditionally" in pred_label else colors.HexColor("#fee2e2")
        badge_fg = colors.HexColor("#166534") if pred_label == "Feasible" else colors.HexColor("#854d0e") if "Conditionally" in pred_label else colors.HexColor("#991b1b")

        kpi_rows = [
            [
                Paragraph("<b>Predicted Feasibility Class</b>", body_style),
                Paragraph("<b>Model Confidence</b>", body_style),
                Paragraph("<b>Feasible Probability</b>", body_style),
                Paragraph("<b>Cond. Feasible</b>", body_style),
                Paragraph("<b>Infeasible</b>", body_style),
            ],
            [
                Paragraph(f"<font color='{badge_fg.hexval()}'><b>{pred_label}</b></font>", body_style),
                Paragraph(f"<b>{feas.get('confidence_percentage', 'N/A')}</b>", body_style),
                Paragraph(f"{(probs.get('Feasible', 0.0) * 100):.1f}%", body_style),
                Paragraph(f"{(probs.get('Conditionally Feasible', 0.0) * 100):.1f}%", body_style),
                Paragraph(f"{(probs.get('Infeasible', 0.0) * 100):.1f}%", body_style),
            ]
        ]
        kpi_table = Table(kpi_rows, colWidths=[120, 95, 95, 100, 100])
        kpi_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#f1f5f9")),
            ('BACKGROUND', (0,1), (-1,1), colors.HexColor("#f8fafc")),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('PADDING', (0,0), (-1,-1), 6),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#cbd5e1")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#e2e8f0")),
        ]))
        story.append(kpi_table)

        # Interpretation
        story.append(Spacer(1, 6))
        story.append(Paragraph(f"<i>{sec_02.get('feasibility_interpretation', '')}</i>", body_style))

        # Embedded Probability Chart
        try:
            chart_bytes = BusinessPlanChartGenerator.generate_probability_chart(probs)
            chart_img = Image(io.BytesIO(chart_bytes), width=480, height=140)
            story.append(Spacer(1, 6))
            story.append(chart_img)
        except Exception:
            pass

        # SHAP Factors
        shap_info = sec_02.get("shap_explainability", {})
        story.append(Spacer(1, 6))
        story.append(Paragraph("<b>2.3 Why Did the AI Give This Result? (SHAP Feature Attribution)</b>", h2_style))
        story.append(Paragraph("<font color='#64748b' size='8'><i>*Note: SHAP reflects non-causal feature contributions toward the model feasibility classification.</i></font>", body_style))

        shap_rows = [
            [Paragraph("<font color='#ffffff'><b>Impact</b></font>", body_style), Paragraph("<font color='#ffffff'><b>Feature Driver</b></font>", body_style), Paragraph("<font color='#ffffff'><b>Observed Value</b></font>", body_style), Paragraph("<font color='#ffffff'><b>Importance</b></font>", body_style), Paragraph("<font color='#ffffff'><b>Business Decision Support Context</b></font>", body_style)]
        ]
        for p in shap_info.get("positive_enablers", [])[:3]:
            shap_rows.append([
                Paragraph("<font color='#16a34a'><b>+ Support</b></font>", body_style),
                Paragraph(f"<b>{p.get('feature')}</b>", body_style),
                Paragraph(str(p.get("feature_value")), body_style),
                Paragraph(str(p.get("relative_importance")), body_style),
                Paragraph(p.get("business_interpretation"), body_style)
            ])
        for n in shap_info.get("negative_hurdles", [])[:3]:
            shap_rows.append([
                Paragraph("<font color='#dc2626'><b>- Hurdle</b></font>", body_style),
                Paragraph(f"<b>{n.get('feature')}</b>", body_style),
                Paragraph(str(n.get("feature_value")), body_style),
                Paragraph(str(n.get("relative_importance")), body_style),
                Paragraph(n.get("business_interpretation"), body_style)
            ])
        shap_table = Table(shap_rows, colWidths=[55, 115, 65, 55, 220])
        shap_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), primary_color),
            ('PADDING', (0,0), (-1,-1), 5),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#cbd5e1")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#e2e8f0")),
        ]))
        story.append(shap_table)

        story.append(Spacer(1, 12))

        # =========================================================================
        # SECTION 03 — STRATEGIC RECOMMENDATIONS & TOPSIS
        # =========================================================================
        sec_03 = report_data.get("section_03", {})
        story.append(Paragraph("SECTION 03 — STRATEGIC RECOMMENDATIONS & TOPSIS RANKING", h1_style))
        story.append(HRFlowable(width="100%", thickness=1.5, color=accent_blue, spaceBefore=0, spaceAfter=8))

        hitl = sec_03.get("human_in_the_loop_selection", {})
        is_sel = hitl.get("is_user_selected", False)
        active_strat_title = hitl.get("selected_strategy_name", "Lean Bootstrapped Launch")
        ai_strat = sec_03.get("ai_recommended_strategy", {})

        # HITL Box
        hitl_bg = colors.HexColor("#ecfdf5") if is_sel else colors.HexColor("#eff6ff")
        hitl_fg = colors.HexColor("#065f46") if is_sel else colors.HexColor("#1e40af")
        hitl_text = hitl.get("alignment_status", "")
        
        story.append(Paragraph(f"<b>Active Operational Strategy:</b> <font color='{hitl_fg.hexval()}'><b>{active_strat_title}</b></font> ({'Adopted by Entrepreneur' if is_sel else 'AI TOPSIS #1 Recommendation'})", body_style))
        story.append(Paragraph(f"<font color='{muted_text.hexval()}'><i>{hitl_text}</i></font>", body_style))
        story.append(Spacer(1, 6))

        # TOPSIS Ranking Table
        story.append(Paragraph("<b>3.1 TOPSIS Multi-Criteria Decision Ranking</b>", h2_style))
        ranking_rows = [
            [Paragraph("<font color='#ffffff'><b>Rank</b></font>", body_style), Paragraph("<font color='#ffffff'><b>Strategy Option</b></font>", body_style), Paragraph("<font color='#ffffff'><b>Focus Area</b></font>", body_style), Paragraph("<font color='#ffffff'><b>Target Capital</b></font>", body_style), Paragraph("<font color='#ffffff'><b>TOPSIS Score</b></font>", body_style)]
        ]
        for r in sec_03.get("strategy_ranking", []):
            ranking_rows.append([
                Paragraph(f"#{r.get('rank')}", body_style),
                Paragraph(f"<b>{r.get('strategy_name')}</b>", body_style),
                Paragraph(r.get("strategic_focus", "Execution"), body_style),
                Paragraph(f"LKR {r.get('estimated_capital_required_lkr', 0):,.0f}", body_style),
                Paragraph(str(r.get("topsis_score", "N/A")), body_style)
            ])
        rank_table = Table(ranking_rows, colWidths=[40, 185, 130, 95, 60])
        rank_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), primary_color),
            ('PADDING', (0,0), (-1,-1), 5),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#cbd5e1")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#e2e8f0")),
        ]))
        story.append(rank_table)

        story.append(Spacer(1, 12))

        # =========================================================================
        # SECTION 04 — FINANCIAL & OPERATIONAL PLAN
        # =========================================================================
        sec_04 = report_data.get("section_04", {})
        story.append(Paragraph("SECTION 04 — FINANCIAL & OPERATIONAL PLAN", h1_style))
        story.append(HRFlowable(width="100%", thickness=1.5, color=accent_blue, spaceBefore=0, spaceAfter=8))
        story.append(Paragraph(f"<font color='#059669'><b>Plan Aligned to Selected Strategy: {active_strat_title}</b></font>", body_style))

        fin_plan = sec_04.get("monthly_financial_plan", {})
        startup = sec_04.get("startup_investment", {})
        funding = sec_04.get("funding_structure", {})

        fin_rows = [
            [Paragraph("<b>Financial Metric</b>", body_style), Paragraph("<b>Allocated Value</b>", body_style), Paragraph("<b>Strategic Planning Guidance</b>", body_style)],
            [Paragraph("Strategy Target Capital", body_style), Paragraph(f"LKR {startup.get('strategy_target_capital_lkr', 0):,.0f}", body_style), Paragraph("Calibrated capital baseline for selected strategy execution.", body_style)],
            [Paragraph("Monthly Operating Budget", body_style), Paragraph(f"LKR {fin_plan.get('monthly_operating_budget_lkr', 0):,.0f}", body_style), Paragraph("Includes overhead, recurring inventory, and utilities.", body_style)],
            [Paragraph("Estimated Monthly Revenue", body_style), Paragraph(f"LKR {fin_plan.get('estimated_monthly_revenue_lkr', 0):,.0f}", body_style), Paragraph("Formula: Customers/Day × Unit Price × Operating Days.", body_style)],
            [Paragraph("Capital Runway Horizon", body_style), Paragraph(f"{funding.get('capital_runway_months', 0)} Months", body_style), Paragraph("Operational survival buffer at baseline operational burn.", body_style)],
            [Paragraph("Funding Gap Status", body_style), Paragraph(startup.get("funding_gap_status", "Fully funded"), body_style), Paragraph("Equity vs external loan financing requirement.", body_style)],
        ]
        fin_table = Table(fin_rows, colWidths=[140, 120, 250])
        fin_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), primary_color),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('PADDING', (0,0), (-1,-1), 5),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#cbd5e1")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#e2e8f0")),
        ]))
        for c in range(3):
            fin_rows[0][c] = Paragraph(f"<font color='#ffffff'><b>{fin_rows[0][c].text.replace('<b>','').replace('</b>','')}</b></font>", body_style)
        story.append(fin_table)

        # Operational Details
        ops = sec_04.get("operational_plan", {})
        staff = ops.get("staffing", {})
        equip = ops.get("equipment", {})
        supp = ops.get("suppliers", {})

        story.append(Spacer(1, 6))
        story.append(Paragraph("<b>4.2 Operational & Resource Allocation</b>", h2_style))
        story.append(Paragraph(f"• <b>Staffing:</b> {staff.get('available_staff_count', 1)} available vs {staff.get('required_staff_count', 1)} required. Status: {staff.get('capacity_status', '')}", bullet_style))
        story.append(Paragraph(f"• <b>Equipment:</b> Score {equip.get('available_equipment_score', '3/5')} vs Req {equip.get('required_equipment_score', '3/5')}. Status: {equip.get('readiness_status', '')}", bullet_style))
        story.append(Paragraph(f"• <b>Suppliers:</b> Availability {supp.get('supplier_availability_score', '3/5')} ({supp.get('network_region', 'Local SME Network')})", bullet_style))

        story.append(Spacer(1, 12))

        # =========================================================================
        # SECTION 05 — SCENARIO ANALYSIS & ACTION ROADMAP
        # =========================================================================
        sec_05 = report_data.get("section_05", {})
        story.append(Paragraph("SECTION 05 — SCENARIO ANALYSIS & ACTION ROADMAP", h1_style))
        story.append(HRFlowable(width="100%", thickness=1.5, color=accent_blue, spaceBefore=0, spaceAfter=8))

        # 5.1 What-If Simulations Table
        story.append(Paragraph("<b>5.1 What-If Sensitivity Simulations</b>", h2_style))
        scen_rows = [
            [Paragraph("<font color='#ffffff'><b>Simulation Scenario</b></font>", body_style), Paragraph("<font color='#ffffff'><b>Predicted Class</b></font>", body_style), Paragraph("<font color='#ffffff'><b>Viability Shift</b></font>", body_style), Paragraph("<font color='#ffffff'><b>Feasible Δ</b></font>", body_style), Paragraph("<font color='#ffffff'><b>Strategic Impact Summary</b></font>", body_style)]
        ]
        for sc in sec_05.get("what_if_analysis", {}).get("scenarios", [])[:4]:
            scen_rows.append([
                Paragraph(f"<b>{sc.get('title')}</b>", body_style),
                Paragraph(sc.get("new_prediction", "Conditionally Feasible"), body_style),
                Paragraph(f"{sc.get('viability_delta', 0.0):+.1%}", body_style),
                Paragraph(f"{sc.get('feasibility_delta', 0.0):+.1%}", body_style),
                Paragraph(sc.get("impact_summary", "Stable sensitivity."), body_style)
            ])
        scen_table = Table(scen_rows, colWidths=[110, 85, 60, 55, 200])
        scen_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), primary_color),
            ('PADDING', (0,0), (-1,-1), 5),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#cbd5e1")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#e2e8f0")),
        ]))
        story.append(scen_table)

        # Counterfactual Box
        cf = sec_05.get("counterfactual_analysis", {})
        story.append(Spacer(1, 6))
        story.append(Paragraph(f"<b>Counterfactual Minimum Viability Threshold:</b> {cf.get('recommendation', 'Capital is adequate.')}", body_style))

        # 5.2 4-Phase Personalized Roadmap
        story.append(Spacer(1, 6))
        story.append(Paragraph("<b>5.2 Time-Phased Action Roadmap & Execution Milestones</b>", h2_style))
        rm = sec_05.get("personalized_action_roadmap", {})
        
        story.append(Paragraph("<b>Phase 1: Immediate Launch (0 – 30 Days):</b>", h2_style))
        for act in rm.get("phase_0_to_30_days", []):
            story.append(Paragraph(f"• {act}", bullet_style))

        story.append(Paragraph("<b>Phase 2: Customer Acquisition & Burn Control (30 – 90 Days):</b>", h2_style))
        for act in rm.get("phase_30_to_90_days", []):
            story.append(Paragraph(f"• {act}", bullet_style))

        story.append(Paragraph("<b>Phase 3: Operational Stabilization & Review (3 – 6 Months):</b>", h2_style))
        for act in rm.get("phase_3_to_6_months", []):
            story.append(Paragraph(f"• {act}", bullet_style))

        story.append(Paragraph("<b>Phase 4: Business Scale & Regional Expansion (6 – 12 Months):</b>", h2_style))
        for act in rm.get("phase_6_to_12_months", []):
            story.append(Paragraph(f"• {act}", bullet_style))

        # 5.3 Measurable KPIs
        story.append(Spacer(1, 6))
        story.append(Paragraph("<b>5.3 Measurable Key Performance Indicators (KPIs)</b>", h2_style))
        kpi_table_data = [
            [Paragraph("<font color='#ffffff'><b>KPI Name</b></font>", body_style), Paragraph("<font color='#ffffff'><b>Target Metric</b></font>", body_style), Paragraph("<font color='#ffffff'><b>Review Frequency</b></font>", body_style), Paragraph("<font color='#ffffff'><b>Category</b></font>", body_style)]
        ]
        for k in sec_05.get("measurable_kpis", []):
            kpi_table_data.append([
                Paragraph(f"<b>{k.get('kpi_name')}</b>", body_style),
                Paragraph(str(k.get("target")), body_style),
                Paragraph(k.get("frequency", "Monthly"), body_style),
                Paragraph(k.get("type", "Operational"), body_style)
            ])
        kpi_doc_table = Table(kpi_table_data, colWidths=[140, 160, 110, 100])
        kpi_doc_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), primary_color),
            ('PADDING', (0,0), (-1,-1), 5),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#cbd5e1")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#e2e8f0")),
        ]))
        story.append(kpi_doc_table)

        # 5.4 Business Constraints & Mitigation Considerations
        story.append(Spacer(1, 6))
        story.append(Paragraph("<b>5.4 Business Constraints & Mitigation Considerations</b>", h2_style))
        for c in sec_05.get("business_constraints_and_mitigation", []):
            story.append(Paragraph(f"• <b>{c.get('constraint')}:</b> {c.get('mitigation')}", bullet_style))

        story.append(Spacer(1, 10))

        # =========================================================================
        # FINAL AI RECOMMENDATION & SUMMARY
        # =========================================================================
        final_box = report_data.get("final_recommendation", {})
        story.append(Paragraph("FINAL AI DECISION RECOMMENDATION", h1_style))
        story.append(HRFlowable(width="100%", thickness=1.5, color=accent_blue, spaceBefore=0, spaceAfter=8))

        rec_table_data = [
            [Paragraph("<b>AI Feasibility Verdict:</b>", body_style), Paragraph(final_box.get("ai_feasibility_verdict", pred_label), body_style)],
            [Paragraph("<b>AI TOPSIS #1 Strategy:</b>", body_style), Paragraph(final_box.get("ai_recommended_strategy", ai_strat.get("strategy_name", "")), body_style)],
            [Paragraph("<b>Entrepreneur Selected Strategy:</b>", body_style), Paragraph(f"<b>{final_box.get('entrepreneur_selected_strategy', active_strat_title)}</b> ({'Adopted Choice' if is_sel else 'Matches AI Rank #1'})", body_style)],
            [Paragraph("<b>Primary Positive Enabler:</b>", body_style), Paragraph(final_box.get("main_positive_strength", "Location Suitability"), body_style)],
            [Paragraph("<b>Primary Operational Hurdle:</b>", body_style), Paragraph(final_box.get("main_operational_constraint", "Working Capital Reserve"), body_style)],
            [Paragraph("<b>Immediate Recommended Action:</b>", body_style), Paragraph(final_box.get("recommended_immediate_next_step", "Finalize operating permits and establish supplier agreements."), body_style)],
        ]
        rec_table = Table(rec_table_data, colWidths=[170, 340])
        rec_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#f8fafc")),
            ('PADDING', (0,0), (-1,-1), 6),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#cbd5e1")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#e2e8f0")),
        ]))
        story.append(rec_table)

        story.append(Spacer(1, 15))
        story.append(Paragraph("<b>Assumptions & Important Disclosures:</b>", h2_style))
        for a in report_data.get("assumptions_and_considerations", []):
            story.append(Paragraph(f"• {a}", bullet_style))

        # Build document
        doc.build(story, canvasmaker=NumberedCanvas)
        buffer.seek(0)
        return buffer.getvalue()
